#ifndef BUZZ_CONTROLLER_QUADMAPPER_NO_SENSING_H
#define BUZZ_CONTROLLER_QUADMAPPER_NO_SENSING_H

#include <argos/buzz_controller_quadmapper.h>
#include <map>
//#include "../../slam/specialized/no_sensing/buzz_slam_no_sensing.h"

using namespace argos;
namespace buzz_quadmapper {

/*
*  Buzz controller to support 3D robust distributed pose graph optimization.
*  This version is tighly coupled with the argos3 simulation without sensing.
*  The fake measurements are generated by adding gaussian noise to the ground truth provided by the simulator.
*/
class CBuzzControllerQuadMapperNoSensing : public CBuzzControllerQuadMapper {

public:

   CBuzzControllerQuadMapperNoSensing();
   
   virtual ~CBuzzControllerQuadMapperNoSensing();

   virtual void Init(TConfigurationNode& t_node);

   // Control functions
   int MoveForwardFakeOdometry(const CVector3& distance, const int& simulation_time_divider);

   buzzvm_state RegisterFunctions();

private:

   int simulation_step_;

};
}
#endif
